import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import {useCountState} from "@/recoil/atoms/Count";
import {useTodoListState} from "@/recoil/atoms/TodoList";
import {useState} from "react";
import * as crypto from "crypto";

export default function Home() {
  const [count, setCount] = useCountState()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main className={styles.main}>
        <h1>Example recoil</h1>
        <div>
          {count}
        </div>
        <div>
          <button onClick={() => setCount((currentValue) => currentValue + 1)}>increment</button>
          <button onClick={() => setCount((currentValue) => currentValue - 1)}>decrement</button>
        </div>
      </main>
    </>
  )
}
